[package]
name = "ldbcollector"
version = "0.1.0"
edition = "2021"

[lib]
name = "ldbcollector"
path = "src/lib.rs"

[[bin]]
name = "ldbcollector-main"
path = "src/main.rs"

[dependencies]
serde = "1.0.117"
serde_derive = "1.0.117"
serde_json = "1.0.59"
iri-string = "0.7.0"
chrono = "0.4.0"
petgraph = "0.6.0"
spdx = "0.10.0"
either = "1.8.1"
multimap = "0.8.3"
libc = "0.2.139"