[package]
name = "ldbcolector"
version = "0.1.0"
edition = "2021"

[lib]
name = "ldbcolector"
path = "src/lib.rs"

[[bin]]
name = "ldbcolector-main"
path = "src/main.rs"

[dependencies]
serde = "1.0.117"
serde_derive = "1.0.117"
serde_json = "1.0.59"
iri-string = "0.7.0"
chrono = "0.4.0"
petgraph = "0.6.0"
spdx = "0.10.0"