name:                LDBcollector
version:             0.1.0.0
github:              "maxhbr/LDBcollector"
license:             BSD3
author:              "Maximilian Huber"
maintainer:          "gh@maximilian-huber.com"
copyright:           "2019 Maximilian Huber"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            A smal tool to collect license metadata, process it and render it in different ways
category:            Development

description:         Please see the README on GitHub at <https://github.com/maxhbr/LDBcollector#readme>

dependencies:
- base >= 4.7 && < 5
- yaml
- aeson
- aeson-pretty
- lens-aeson
- lens
- text
- vector
- filepath
- bytestring
- unordered-containers
- cassava
- directory
- opensource
- transformers
- containers
- raw-strings-qq
- hexml
- lucid
- http-client
- pandoc
- pandoc-types
- file-embed
- graphviz

library:
  source-dirs: src

executables:
  LDBcollector-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LDBcollector
    - pandoc

tests:
  LDBcollector-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LDBcollector
    - hspec
    - QuickCheck
