name:                LDBcollector
version:             0.1.0.0
github:              "githubuser/LDBcollector"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/LDBcollector#readme>

dependencies:
- base >= 4.7 && < 5
- yaml
- aeson
- aeson-pretty
- lens-aeson
- lens
- text
- vector
- filepath
- bytestring
- unordered-containers
- cassava
- directory
- opensource
- transformers
- containers
- raw-strings-qq
- hexml
- lucid

library:
  source-dirs: src

executables:
  LDBcollector-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LDBcollector
    - pandoc

tests:
  LDBcollector-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LDBcollector
    - hspec
    - QuickCheck
