name:                LDBcollector
version:             0.1.0.0
github:              "maxhbr/LDBcollector"
license:             BSD3
author:              "Maximilian Huber"
maintainer:          "gh@maximilian-huber.com"
copyright:           "2019 Maximilian Huber"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            A small tool to collect license metadata, process it and render it in different ways
category:            Development

description:         Please see the README on GitHub at <https://github.com/maxhbr/LDBcollector#readme>

dependencies:
- aeson
- aeson-pretty
- attoparsec
- base >= 4.7 && < 5
- base16-bytestring
- bytestring
- cassava
- containers
- cryptohash-md5
- curl
- directory
- extra
- file-embed
- filepath
- graphviz
- hashable
- hexml
- http-client
- lens
- lens-aeson
- lucid
- mtl
- network-uri
- opensource
- pandoc
- pandoc-types
- raw-strings-qq
- text
- transformers
- unordered-containers
- vector
- yaml

library:
  source-dirs: src

executables:
  LDBcollector-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LDBcollector
    - pandoc

tests:
  LDBcollector-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LDBcollector
    - hspec
    - QuickCheck
