name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        enable-stack: true
        stack-version: 'latest'

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-stack
      with:
        path:
          - ~/.stack
          - .stack-work
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - run: |
        sudo apt-get update
        sudo apt-get install -y graphviz libghc-curl-dev

    - run: stack build
    - run: stack test
    - run: stack exec LDBcollector-exe
    - uses: actions/upload-artifact@v2
      with:
        name: LDBcollector-exe-result
        path: _generated
